reduced the number if docker images used and reduced the size
GoogleCloudPlatform/gke-networking-demos pull request #13
Opened 2018-12-17 17:07 UTC by emailbob

Forgot to add this to the last PR
- Updated the readme and checks to the new service backend requirement
- The demo was using two container images nginx(109MB) and gcr.io/k8s-testimages/kettle:latest(870MB). I replaced both images with a new container gcr.io/pso-examples/nginx-curl(19.3MB)
- The my-nginx deployment is now running one container in the pod instead of two

2018-12-17 17:28 UTC, chrislovecnm requested changes

2018-12-17 17:28 UTC, chrislovecnm commented on container/Dockerfile
> +# Copyright 2018 Google LLC
Need a cloudbuild.xml file for CI

2018-12-17 20:16 UTC, emailbob commented
test this please

2018-12-17 20:21 UTC, emailbob commented
test this please

2018-12-17 20:29 UTC, emailbob commented
test this please

2018-12-26 20:39 UTC, emailbob commented on container/Dockerfile
> +# Copyright 2018 Google LLC
Added cloudbuild.yaml

2018-12-28 16:09 UTC, emailbob commented
test this please

2018-12-28 16:09 UTC, chrislovecnm approved these changes

2018-12-28 16:55 UTC, merged