Basic changes for Jenkins
GoogleCloudPlatform/gke-networking-demos pull request #3
Opened 2018-09-07 21:33 UTC by techgnosis

* Jenkinsfile
* kubectl namespacing
* whitespace

2018-09-07 22:37 UTC, chrislovecnm requested changes
Looks great overall. Just would love some code level docs in the Jenkinsfiles.

2018-09-07 22:37 UTC, chrislovecnm commented on Jenkinsfile
>    stages {
Total nit pick, but can we please get some code level documentation in for the different stages.  Thanks

2018-09-07 22:45 UTC, techgnosis commented
test this please

2018-09-08 14:36 UTC, chrislovecnm approved these changes

2018-09-08 14:36 UTC, chrislovecnm commented
/lgtm

2018-09-08 14:36 UTC, merged