Converting Deployment Manager code to TerraForm. Some of DM files hav…
GoogleCloudPlatform/gke-networking-demos pull request #30
Opened 2019-04-26 17:19 UTC by homernajafi

…e not been deleted because gke-to-gke-peering is still using them.

This Terraform code can be improved by using TF Loops but it's a time consuming task (in case we want to assign time to it)

2019-04-26 21:05 UTC, chrislovecnm requested changes
Looks good mostly nit picks :)

2019-04-26 21:05 UTC, chrislovecnm commented on gke-to-gke-vpn/terraform/main.tf
> +resource "google_container_cluster" "cluster-deployment-cluster1" {
We need code level documentation on all of the terraform.

2019-04-26 21:05 UTC, chrislovecnm commented on gke-to-gke-vpn/terraform/main.tf
> +  location = "us-east1-b"
Can we make this a variable?

2019-04-26 21:05 UTC, chrislovecnm commented on gke-to-gke-vpn/terraform/main.tf
> +  location           = "${var.cluster1-location}"
Conceal meta data?  What else are we missing?

2019-04-26 21:05 UTC, chrislovecnm commented on gke-to-gke-vpn/terraform/network.tf
> +  region  = "us-east1"
again lets make this a variable, and set two different regions.

2019-04-26 21:05 UTC, chrislovecnm commented on gke-to-gke-vpn/terraform/variables.tf
> +#  default     = "homer-proj"
remove

2019-04-26 21:06 UTC, chrislovecnm commented
@homernajafi CI is failing :(

2019-04-26 21:13 UTC, homernajafi commented
whitespace issue. good comments. I will fix those.

2019-04-29 18:38 UTC, homernajafi commented
test this please

2019-04-30 15:03 UTC, homernajafi commented
Test this please

2019-04-30 16:16 UTC, homernajafi commented
Test this please

2019-04-30 17:34 UTC, homernajafi commented
Test this please

2019-05-01 15:19 UTC, homernajafi commented
Test this please

2019-05-01 16:52 UTC, homernajafi commented
Test this please

2019-05-01 17:01 UTC, homernajafi commented
Test this please

2019-05-01 17:08 UTC, homernajafi commented
Test this please

2019-05-01 17:59 UTC, homernajafi commented
Test this please

2019-05-01 18:37 UTC, homernajafi commented
Test this please

2019-05-01 19:04 UTC, homernajafi commented
Test this please

2019-05-01 19:37 UTC, homernajafi commented
Test this please

2019-05-01 20:51 UTC, homernajafi commented
Test this please

2019-05-01 21:01 UTC, homernajafi commented
Test this please

2019-05-01 21:34 UTC, homernajafi commented
Test this please

2019-05-01 22:52 UTC, homernajafi commented
Test this please

2019-05-02 15:53 UTC, chrislovecnm reviewed
Can we add back in deployment manager, and see if we can get that passing, otherwise we will disable for now. 

Also we need to update the documentation for the prerequisites, and talk about terraform.  Please check with Kristen if we need to update a quicklab that corresponds to this as well.

2019-05-02 16:19 UTC, homernajafi commented
CI is passing. I will talk to Kristen about doc. I will try to finish before I leave.

2019-05-02 16:50 UTC, chrislovecnm approved these changes

2019-05-02 16:51 UTC, chrislovecnm commented
@homernajafi I am going to merge, and let you work on docs in a separate PR.

2019-05-02 16:51 UTC, merged